language: node_js
node_js:
  - "16"
dist: trusty
sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cliscript:
- ng lint
- ng build --prod --base-href https://fouomene.github.io/angular-tour-of-heroes/